[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[redirects]]
  from = "https://evanjustevan.com/just-evan/*"
  to = "https://publish.obsidian.md/serve?url=evanjustevan.com/just-evan/:splat"
  status = 200
  force = true
  